DICT_DIR = "~/Downloads/Language/mdict"
MDICT_TEMP_ASSETS_DIR = "~/.mdict/res"
SERVER_IP = "127.0.0.1"
SERVER_PORT = "8808"
SPEEXDEC = "/usr/local/bin/speexdec"
DEFAULT_DICT = "DLE_v23.8_1_RealAcademia2026-mdict/DLE_v23.8.1_RealAcademia2026.mdx"
# NO_BROWSER = "true"
